---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doom-deploy
  namespace: kubedoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doom-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: doom-app
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom
        ports:
        - containerPort: 5900
          protocol: TCP
